version: 2

jobs:
  build:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/.dotfiles/

    steps:
      - checkout

      - run:
          name: Install Sudo
          command: |
            apt update
            apt install -y sudo

      - run:
          name: Install Git
          command: |
            apt install -y git

      - run:
          name: Install Known Host (github.com)
          command: |
            ssh -oStrictHostKeyChecking=accept-new git@github.com || true

      - run:
          name: Run Install Script
          command: |
            cd install-scripts/
            ./install.sh
